# Generated by Django 3.2.16 on 2023-01-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, max_length=25, upload_to='images', width_field=50),
        ),
    ]
