# Generated by Django 3.2.16 on 2023-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(blank=True, max_length=25, upload_to='blog/static/images', width_field=50),
        ),
    ]
